#ifndef ERGOTYPE_PLATFORM_HID_REPORTS_H
#define ERGOTYPE_PLATFORM_HID_REPORTS_H

enum {
    REPORT_ID_KEYBOARD = 1,
    REPORT_ID_CONSUMER = 2,
    REPORT_ID_MOUSE = 3,
};

#define HID_NKRO_KEY_BYTES 32
#define HID_CONSUMER_USAGE_COUNT 6
#define HID_CONSUMER_REPORT_BYTES 12
#define HID_MOUSE_REPORT_BYTES 9

#define CONFIG_PROTOCOL_VERSION 1
#define CONFIG_MESSAGE_SIZE 63
#define CONFIG_STATUS_MODE_HID 0
#define CONFIG_STATUS_PROFILE_NKRO 1

#endif
