name: Build and Test ErgoType Firmware

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read  # Required by actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Clone submodules recursively

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install cmake gcc-arm-none-eabi build-essential -y

    - name: Setup Pico SDK
      run: |
        mkdir -p ~/.pico-sdk
        git clone --recurse-submodules https://github.com/raspberrypi/pico-sdk.git --branch 2.0.0 ~/.pico-sdk
    
    - name: Modify ffconf.h to Set FF_USE_STRFUNC=1
      run: |
        sed -i 's/^#define FF_USE_STRFUNC.*/#define FF_USE_STRFUNC  1/' ~/.pico-sdk/lib/tinyusb/lib/fatfs/source/ffconf.h
        cat ~/.pico-sdk/lib/tinyusb/lib/fatfs/source/ffconf.h | grep "FF_USE_STRFUNC"

    - name: Configure Pico SDK Path
      run: echo "PICO_SDK_PATH=$HOME/.pico-sdk" >> $GITHUB_ENV

    - name: Build Project
      env:
        PICO_SDK_PATH: ${{ env.PICO_SDK_PATH }}
      run: |
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)

    - name: Verify Firmware Binary
      run: |
        test -f build/ErgoType.uf2

    - name: Upload Firmware Artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware-uf2
        path: build/ErgoType.uf2
